#define HASH_TABLE_SIZE     0x4000
#define FRAME_STACK_SIZE    0x1000
#define VARDEC              0
#define FUNCDEC             1
#define STRUCTDEF           2
#define FUNCDEF             3
#define TRUE                1
#define FALSE               0
#define PARAMDEC            4
#define FIELDDEC            5
#define FIELD_TYPE_PARAM    0
#define FIELD_TYPE_STRUCT   1